/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.tables.records;


import edu.java.domain.jooq.tables.StackoverflowQuestion;

import java.beans.ConstructorProperties;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class StackoverflowQuestionRecord extends TableRecordImpl<StackoverflowQuestionRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>STACKOVERFLOW_QUESTION.LINK_ID</code>.
     */
    public void setLinkId(@Nullable Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>STACKOVERFLOW_QUESTION.LINK_ID</code>.
     */
    @Nullable
    public Long getLinkId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>STACKOVERFLOW_QUESTION.ANSWER_COUNT</code>.
     */
    public void setAnswerCount(@NotNull Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>STACKOVERFLOW_QUESTION.ANSWER_COUNT</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getAnswerCount() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return StackoverflowQuestion.STACKOVERFLOW_QUESTION.LINK_ID;
    }

    @Override
    @NotNull
    public Field<Long> field2() {
        return StackoverflowQuestion.STACKOVERFLOW_QUESTION.ANSWER_COUNT;
    }

    @Override
    @Nullable
    public Long component1() {
        return getLinkId();
    }

    @Override
    @NotNull
    public Long component2() {
        return getAnswerCount();
    }

    @Override
    @Nullable
    public Long value1() {
        return getLinkId();
    }

    @Override
    @NotNull
    public Long value2() {
        return getAnswerCount();
    }

    @Override
    @NotNull
    public StackoverflowQuestionRecord value1(@Nullable Long value) {
        setLinkId(value);
        return this;
    }

    @Override
    @NotNull
    public StackoverflowQuestionRecord value2(@NotNull Long value) {
        setAnswerCount(value);
        return this;
    }

    @Override
    @NotNull
    public StackoverflowQuestionRecord values(@Nullable Long value1, @NotNull Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StackoverflowQuestionRecord
     */
    public StackoverflowQuestionRecord() {
        super(StackoverflowQuestion.STACKOVERFLOW_QUESTION);
    }

    /**
     * Create a detached, initialised StackoverflowQuestionRecord
     */
    @ConstructorProperties({ "linkId", "answerCount" })
    public StackoverflowQuestionRecord(@Nullable Long linkId, @NotNull Long answerCount) {
        super(StackoverflowQuestion.STACKOVERFLOW_QUESTION);

        setLinkId(linkId);
        setAnswerCount(answerCount);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised StackoverflowQuestionRecord
     */
    public StackoverflowQuestionRecord(edu.java.domain.jooq.tables.pojos.StackoverflowQuestion value) {
        super(StackoverflowQuestion.STACKOVERFLOW_QUESTION);

        if (value != null) {
            setLinkId(value.getLinkId());
            setAnswerCount(value.getAnswerCount());
            resetChangedOnNotNull();
        }
    }
}
