app:
  scheduler:
    enable: true
    interval: 100s
    force-check-delay: 100s
  stack-overflow-url:
    default-url: https://api.stackexchange.com/2.3
  git-hub-url:
    default-url: https://api.github.com
  bot-link:
    link: http://localhost:8090
  database-access-type: JPA


spring:
  application:
    name: scrapper
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5433/scrapper"
    username: postgres
    password: postgres
  liquibase:
    enabled: false


server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  show-actuator: true
  swagger-ui:
    path: /scrapper/swagger-ui
