app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
  stack-overflow-url:
    default-url: https://api.stackexchange.com/2.3
  git-hub-url:
    default-url: https://api.github.com
  bot-link:
    link: http://localhost:8080

spring:
  application:
    name: scrapper
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/scrapper}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  liquibase:
    enabled: false


server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  show-actuator: true
  swagger-ui:
    path: /scrapper/swagger-ui
