/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.tables;


import edu.java.domain.jooq.DefaultSchema;
import edu.java.domain.jooq.Keys;
import edu.java.domain.jooq.tables.records.LinkageRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Linkage extends TableImpl<LinkageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>LINKAGE</code>
     */
    public static final Linkage LINKAGE = new Linkage();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<LinkageRecord> getRecordType() {
        return LinkageRecord.class;
    }

    /**
     * The column <code>LINKAGE.CHAT_ID</code>.
     */
    public final TableField<LinkageRecord, Long> CHAT_ID = createField(DSL.name("CHAT_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>LINKAGE.LINK_ID</code>.
     */
    public final TableField<LinkageRecord, Long> LINK_ID = createField(DSL.name("LINK_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    private Linkage(Name alias, Table<LinkageRecord> aliased) {
        this(alias, aliased, null);
    }

    private Linkage(Name alias, Table<LinkageRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>LINKAGE</code> table reference
     */
    public Linkage(String alias) {
        this(DSL.name(alias), LINKAGE);
    }

    /**
     * Create an aliased <code>LINKAGE</code> table reference
     */
    public Linkage(Name alias) {
        this(alias, LINKAGE);
    }

    /**
     * Create a <code>LINKAGE</code> table reference
     */
    public Linkage() {
        this(DSL.name("LINKAGE"), null);
    }

    public <O extends Record> Linkage(Table<O> child, ForeignKey<O, LinkageRecord> key) {
        super(child, key, LINKAGE);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @NotNull
    public UniqueKey<LinkageRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_3559;
    }

    @Override
    @NotNull
    public List<ForeignKey<LinkageRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_35, Keys.CONSTRAINT_355);
    }

    private transient Chats _chats;
    private transient Links _links;

    /**
     * Get the implicit join path to the <code>PUBLIC.CHATS</code> table.
     */
    public Chats chats() {
        if (_chats == null)
            _chats = new Chats(this, Keys.CONSTRAINT_35);

        return _chats;
    }

    /**
     * Get the implicit join path to the <code>PUBLIC.LINKS</code> table.
     */
    public Links links() {
        if (_links == null)
            _links = new Links(this, Keys.CONSTRAINT_355);

        return _links;
    }

    @Override
    @NotNull
    public Linkage as(String alias) {
        return new Linkage(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public Linkage as(Name alias) {
        return new Linkage(alias, this);
    }

    @Override
    @NotNull
    public Linkage as(Table<?> alias) {
        return new Linkage(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public Linkage rename(String name) {
        return new Linkage(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public Linkage rename(Name name) {
        return new Linkage(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public Linkage rename(Table<?> name) {
        return new Linkage(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Long, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Long, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
