/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq;


import edu.java.domain.jooq.tables.Chats;
import edu.java.domain.jooq.tables.GithubBranches;
import edu.java.domain.jooq.tables.Linkage;
import edu.java.domain.jooq.tables.Links;
import edu.java.domain.jooq.tables.StackoverflowQuestion;
import edu.java.domain.jooq.tables.records.ChatsRecord;
import edu.java.domain.jooq.tables.records.GithubBranchesRecord;
import edu.java.domain.jooq.tables.records.LinkageRecord;
import edu.java.domain.jooq.tables.records.LinksRecord;
import edu.java.domain.jooq.tables.records.StackoverflowQuestionRecord;

import javax.annotation.processing.Generated;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ChatsRecord> CONSTRAINT_3 = Internal.createUniqueKey(Chats.CHATS, DSL.name("CONSTRAINT_3"), new TableField[] { Chats.CHATS.ID }, true);
    public static final UniqueKey<LinkageRecord> CONSTRAINT_3559 = Internal.createUniqueKey(Linkage.LINKAGE, DSL.name("CONSTRAINT_3559"), new TableField[] { Linkage.LINKAGE.CHAT_ID, Linkage.LINKAGE.LINK_ID }, true);
    public static final UniqueKey<LinksRecord> CONSTRAINT_4 = Internal.createUniqueKey(Links.LINKS, DSL.name("CONSTRAINT_4"), new TableField[] { Links.LINKS.ID }, true);
    public static final UniqueKey<LinksRecord> CONSTRAINT_45 = Internal.createUniqueKey(Links.LINKS, DSL.name("CONSTRAINT_45"), new TableField[] { Links.LINKS.URL }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<GithubBranchesRecord, LinksRecord> CONSTRAINT_5 = Internal.createForeignKey(GithubBranches.GITHUB_BRANCHES, DSL.name("CONSTRAINT_5"), new TableField[] { GithubBranches.GITHUB_BRANCHES.LINK_ID }, Keys.CONSTRAINT_4, new TableField[] { Links.LINKS.ID }, true);
    public static final ForeignKey<LinkageRecord, ChatsRecord> CONSTRAINT_35 = Internal.createForeignKey(Linkage.LINKAGE, DSL.name("CONSTRAINT_35"), new TableField[] { Linkage.LINKAGE.CHAT_ID }, Keys.CONSTRAINT_3, new TableField[] { Chats.CHATS.ID }, true);
    public static final ForeignKey<LinkageRecord, LinksRecord> CONSTRAINT_355 = Internal.createForeignKey(Linkage.LINKAGE, DSL.name("CONSTRAINT_355"), new TableField[] { Linkage.LINKAGE.LINK_ID }, Keys.CONSTRAINT_4, new TableField[] { Links.LINKS.ID }, true);
    public static final ForeignKey<StackoverflowQuestionRecord, LinksRecord> CONSTRAINT_9 = Internal.createForeignKey(StackoverflowQuestion.STACKOVERFLOW_QUESTION, DSL.name("CONSTRAINT_9"), new TableField[] { StackoverflowQuestion.STACKOVERFLOW_QUESTION.LINK_ID }, Keys.CONSTRAINT_4, new TableField[] { Links.LINKS.ID }, true);
}
