/*
 * This file is generated by jOOQ.
 */

package edu.java.domain.jooq;

import edu.java.domain.jooq.tables.Chats;
import edu.java.domain.jooq.tables.GithubBranches;
import edu.java.domain.jooq.tables.Linkage;
import edu.java.domain.jooq.tables.Links;
import edu.java.domain.jooq.tables.StackoverflowQuestion;
import javax.annotation.processing.Generated;

/**
 * Convenience access to all tables in the default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Tables {

    /**
     * The table <code>CHATS</code>.
     */
    public static final Chats CHATS = Chats.CHATS;

    /**
     * The table <code>GITHUB_BRANCHES</code>.
     */
    public static final GithubBranches GITHUB_BRANCHES = GithubBranches.GITHUB_BRANCHES;

    /**
     * The table <code>LINKAGE</code>.
     */
    public static final Linkage LINKAGE = Linkage.LINKAGE;

    /**
     * The table <code>LINKS</code>.
     */
    public static final Links LINKS = Links.LINKS;

    /**
     * The table <code>STACKOVERFLOW_QUESTION</code>.
     */
    public static final StackoverflowQuestion STACKOVERFLOW_QUESTION = StackoverflowQuestion.STACKOVERFLOW_QUESTION;
}
